[theme]
primaryColor = "#c71585"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F0F5"
textColor = "#333333"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false